version: "3"
services:

  pulsebs-server:
    image: "jackgorga/pulsebs:server"
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3001:3001"

  pulsebs-client:
    image: "jackgorga/pulsebs:client"
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    stdin_open: true
