version: "3"
services:

  pulsebs-server:
    image: "team14se2/pulsebs:serverRelease2"
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3001:3001"

  pulsebs-client:
    image: "team14se2/pulsebs:clientRelease2"
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    stdin_open: true
